version: "3"

networks:
  traefik:
    external: true
  internal:
    external: false

services:
  xmorphus_server:
    image: node:carbon
    command: bash -c "npm install && npx gulp serve"
    # depends_on:
    #   - moongo
    working_dir: "/home/node"
    volumes:
      - './:/home/node/:cached'
    networks:
      - traefik
      - internal
    labels:
      - "traefik.backend=xmorphus_server"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:xm.localhost"
      - "traefik.enable=true"
      - "traefik.port=9000"
    environment:
      HOST: 0.0.0.0
      PORT: 9000

  # moongo:
  #   image: mongo
  #   restart: always
  #   command: mongod --port 5442
  #   environment:
  #     MONGO_DATA_DIR: /data/db
  #   networks:
  #     - internal
  #   labels:
  #     - "traefik.enable=false" # wont display at http://traefik.localhost
  #     - "traefik.backend=moongo"
  #     - "traefik.docker.network=internal"
  #     - "traefik.port=5442"
  #   # persists outside of docker
  #   volumes:
  #     - ./data/db:/data/db
