version: "3"

networks:
  traefik:
    external: true

services:
  xmorphus:
    image: node:12-slim
    command: bash -c "npm install && npx gulp serve"
    working_dir: "/home/node"
    volumes:
      - './:/home/node/:cached'
    networks:
      - traefik
    labels:
      - "traefik.backend=xmorphus"
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.port=9090"
    environment:
      HOST: 0.0.0.0
      PORT: 9090
